chore(android): upgrade hilt to 2.51 (#4056)
The error I was getting was:

```error
java.lang.RuntimeException: Cannot create an instance of class dev.firezone.android.features.splash.ui.SplashViewModel
Caused by: java.lang.NoSuchMethodException: dev.firezone.android.features.splash.ui.SplashViewModel.<init> []
```

I'm not sure how hilt works, but I saw a package for the hilt compiler
that was version 2.50. After upgrading that, the crash stopped
happening. My best guess is that the compiler needs to be on the same
version, otherwise it doesn't work?